# Generated by Django 4.2 on 2023-04-11 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('dt', models.DateTimeField()),
                ('countPeople', models.IntegerField()),
                ('placeX', models.CharField(max_length=128)),
                ('placeY', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Party2User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patyPlace.party')),
                ('userField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patyPlace.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('partyField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patyPlace.party')),
                ('userField', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patyPlace.authuser')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.BooleanField()),
                ('party2user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patyPlace.party2user')),
            ],
        ),
    ]
