# Generated by Django 4.2 on 2023-04-14 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patyPlace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='creatorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patyPlace.authuser'),
        ),
        migrations.AddField(
            model_name='party',
            name='images',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
