# Generated by Django 4.2 on 2023-04-14 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patyPlace', '0002_party_creatorid_party_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='creatorId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='patyPlace.authuser'),
        ),
    ]
