# Generated by Django 4.2 on 2023-04-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patyPlace', '0004_alter_party_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='dt',
            field=models.DateField(),
        ),
    ]
