# Generated by Django 4.2 on 2023-04-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patyPlace', '0008_alter_party_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='placeX',
        ),
        migrations.RemoveField(
            model_name='party',
            name='placeY',
        ),
        migrations.AddField(
            model_name='party',
            name='adres',
            field=models.CharField(max_length=288, null=True),
        ),
    ]
