# Generated by Django 4.2 on 2023-04-18 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patyPlace', '0009_remove_party_placex_remove_party_placey_party_adres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='creatorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='patyPlace.authuser'),
        ),
    ]
