# Generated by Django 4.1.4 on 2023-04-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patyPlace', '0010_alter_party_creatorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='adres',
            field=models.CharField(max_length=288, null=True, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='party',
            name='countPeople',
            field=models.IntegerField(verbose_name='Количество людей'),
        ),
        migrations.AlterField(
            model_name='party',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='party',
            name='dt',
            field=models.DateField(max_length=20, verbose_name='Дата вечеринки'),
        ),
        migrations.AlterField(
            model_name='party',
            name='images',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='party',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
    ]
